config/routes.rb
White::Application.routes.draw do

  match '/lib/libruary', :to => 'Lib#libruary'
  match '/lib/showall', :to => 'Lib#showall'
  match '/lib/add', :to => 'Lib#add'
  match '/lib/odna', :to => 'Lib#odna'

  match '/post/posts', :to => 'Post#posts'

  match '/sessions/login', :to => 'sessions#login'
  match '/sessions/logout', :to => 'sessions#logout'
  match '/sessions/signup', :to => 'sessions#signup'

  match '/servis/calc', :to => 'Servis#calc'
  match '/servis/alph', :to => 'Servis#alph'
  match '/servis', :to => 'Pages#servis'
  root :to => 'Pages#home'
    

end

app/models/book.rb
class Book < ActiveRecord::Base

 



end

app/models/mposts.rb
class Mposts < ActiveRecord::Base
end

app/models/razd.rb
class Razd < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


end

app/controllers/lib_controller.rb
class LibController < ApplicationController

  def add
    @ad = true
    @lbr = true


    if params["commit"] == "Add"

      bk = Book.new(:avtor => params["avtor"], :razdel => params["list"]["ida"], :komment => params["komment"], :nazv => params["nazv"] )
      bk = bk.save

      @hg = ""
    end
  end

  def showall
    @lbr = true
    @shw = true
    @sw = Book.all
    @otf = ""
    if params["commit"] == "Search"
      @otf = " "
      @vibraz = params["list"]["ida"]

    end
    if params["commit"] == "Cancel"
      @otf = ""
      
    end

  end

  def odna  
    @lbr = true
    @odn = true
    @bookk = Book.find(params[:id])

  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def servis
end

end

app/controllers/post_controller.rb
class PostController < ApplicationController

def posts
 @pst = Mposts.all
  if params["commit"] == "get"

    ps = Mposts.new(:userh => cookies[:usr], :text => params["figna"])
    ps = ps.save
    redirect_to post_posts_path
  end

end

end

app/controllers/servis_controller.rb
class ServisController < ApplicationController

  def calc
  @clc = true  

    if params["commit"] == "="
      znak = params["one"].scan(/[*+|-]/)
      tmp = Array.new
      t = params["one"]

      for f in 0..t.length-1
        tmp << ""
      end

      j = 0
      jj = 0
      while j <= t.length-1
        if t[j] == "+" or t[j] == "-" or t[j] == "*"  or t[j] == "|"
          j = j+1
          jj = jj+1
        else
          tmp[jj] = tmp[jj].to_s << t[j].to_s
          j = j+1
        end 
      end
      tmp.delete("")

      @rez = 0
      if znak[0] == "*"  
        @rez = 1
      end 
      for i in 1..tmp.length-1
      
        if i == 1 
          @rez = tmp[0].to_i
        end
      

        if znak[i-1] == "+" 
          @rez = @rez + tmp[i].to_i
        end
       

        if znak[i-1] == "-" 
          @rez = @rez - tmp[i].to_i
        end


        if znak[i-1] == "*"
          @rez = @rez * tmp[i].to_i
        end

        if znak[i-1] == "|"
          @rez = @rez / tmp[i].to_i
        end     

      end
      
    end

    if params["commit"] == "+"
      @calc = params["one"] + "+"
    end

    if params["commit"] == "-"
      @calc = params["one"] + "-"
    end

    if params["commit"] == "*"
      @calc = params["one"] + "*"
    end

    if params["commit"] == "/"
      @calc = params["one"] + "|"
    end


    if params["commit"] == "1"
      @calc = params["one"] + "1"
    end
    if params["commit"] == "2"
      @calc = params["one"] + "2"
    end
    if params["commit"] == "3"
      @calc = params["one"] + "3"
    end
    if params["commit"] == "4"
      @calc = params["one"] + "4"
    end
    if params["commit"] == "5"
      @calc = params["one"] + "5"
    end
    if params["commit"] == "6"
      @calc = params["one"] + "6"
    end
    if params["commit"] == "7"
      @calc = params["one"] + "7"
    end
    if params["commit"] == "8"
      @calc = params["one"] + "8"
    end
    if params["commit"] == "9"
      @calc = params["one"] + "9"
    end
    if params["commit"] == "0"
      @calc = params["one"] + "0"
    end
    if params["commit"] == "  CE  "
      @calc = ""
    end
      
  end


  def alph
  @alp = true  

    t = params["txt"]
    if t.nil? 
      t = ""
    end
    t = t.split(/ /)
    t = t.sort
    @rezult = t.join(" ")
    
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def login

  if params["commit"] == "Войти"

   @t = User.find_by_login(params["login"])
    if @t.pass ==  params["password"]

      cookies[:usr] =  params["login"]
      redirect_to root_path  
    end

  end

end


def logout

  cookies.delete(:usr)
  redirect_to root_path    
end

def signup
  if params["commit"] == "signup"

    us = User.new(:login => params["login"], :email => params["email"], :pass => params["password"] )
    us = us.save

    cookies[:usr] =  params["login"]

    redirect_to root_path  
flash[:notice] = "Thanks for your comment!"  
  end
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lib_helper.rb
module LibHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/servis_helper.rb
module ServisHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>

          <% if @clc == true %>

      <li><%= link_to "Sortirovka", servis_alph_path %></li>  

          <% end %>


          <% if @alp == true %>

      <li><%= link_to "Calculator", servis_calc_path %></li>  

          <% end %>


          <% if @ad == true %>

      <li><%= link_to "showall", lib_showall_path %></li>
      <li><%= link_to "libruary", lib_libruary_path %></li>

          <% end %>



          <% if @shw == true %>


      <li><%= link_to "Add", lib_add_path %></li>
      <li><%= link_to "libruary", lib_libruary_path %></li>

          <% end %>

          <% if @odn == true %>


      <li><%= link_to "Add", lib_add_path %></li>
      <li><%= link_to "showall", lib_showall_path %></li>
      <li><%= link_to "libruary", lib_libruary_path %></li>

          <% end %>



      <li><%= link_to "Home", root_path %></li>  

    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="round">
    <ul>

      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Servises", servis_path %></li>
      <li><%= link_to "libruary", lib_libruary_path %></li>
          <% if cookies[:usr].nil? %>
            <li><%= link_to "Login", sessions_login_path %></li>
            <li><%= link_to "Signup", sessions_signup_path %></li>
          <% else %>
            <li><%= link_to "Posts", post_posts_path %></li>
            <li><%= link_to "Logout", sessions_logout_path %></li>
            <%= cookies[:usr] %>
          <% end %>
 </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>White</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
      <%= render 'layouts/header' %>

      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>

      <%= render 'layouts/footer' %>
    </div>

</body>
</html>

app/views/lib/add.html.erb
Добавить книгу
<%= @tmp %>

<%= form_tag '/lib/add' do %>
  Раздел
  <%= collection_select(:list, :ida, Razd.all, :name, :name) %><br />
  Автор
  <%= text_field_tag :avtor, @hg %><br />
  Название
  <%= text_field_tag :nazv, "" %><br />
  Коментарий
  <%= text_area_tag :komment, "" %><br />



  <%= submit_tag "Add" %><br />
<% end %>


app/views/lib/libruary.html.erb
Типа книги


<li><%= link_to "Показать все", lib_showall_path %></li>
<li><%= link_to "Добавить книгу", lib_add_path %></li>

app/views/lib/odna.html.erb
книга какая-то
<h1><%= @bookk.razdel %></h1>
<h1><%= @bookk.avtor %></h1>
<h1><%= @bookk.nazv %></h1>
<h1><%= @bookk.komment %></h1>

<%= @prov %>

app/views/lib/showall.html.erb
Типа фильтр:<br />

<%= form_tag '/lib/showall' do %>
Искать по разделу:

  <%= collection_select(:list, :ida, Razd.all, :name, :name) %><br />



  <%= submit_tag "Search" %>

    <%= form_tag '/lib/showall' do %>
     <%= submit_tag "Cancel" %>
    <% end %>

<br />
<% end %>



<br />


<%if @otf == ""  %>


Типа все книги :<br /> 

<%@sw.each do |p| %>
  

 <%=p.razdel%>
 <%=p.avtor%>
 <%=p.nazv%>
 <%= link_to "pokaz", {:action => 'odna', :id => p.id} -%><br />

<% end %>   




<% else %>   

  <%@sw.each do |p| %>
    <%if p.razdel == @vibraz %>

     <%=p.razdel%>
     <%=p.avtor%>
     <%=p.nazv%>
     <%= link_to "pokaz", {:action => 'odna', :id => p.id} -%><br />

    <% end %>   
  <% end %>   
<% end %>


<br />



app/views/pages/home.html.erb
<h1>Home page</h1>
<p>
Servisesi:
<li><%= link_to "Servisesi", servis_path %></li>
<li><%= link_to "Libruary", lib_libruary_path %></li>

</p>

app/views/pages/servis.html.erb
<h1>SEERVISESI</h1>
<p>
Servisesi:
<li><%= link_to "Calculator", servis_calc_path %></li>
<li><%= link_to "Sotrirovka", servis_alph_path %></li>


</p>

app/views/post/posts.html.erb
<h1>Пост всякой фигни</h1>

 <% @pst.each do |p| %>
   <%=p.userh%>:
   <%=p.text%><br /><br />


 <% end %>

<%= form_tag '/post/posts' do %>
  Текст вашей фигни<br />
  <%= text_field_tag :figna, "" %>

  <%= submit_tag "get" %><br /><br />
<% end %>


app/views/servis/alph.html.erb
<%= form_tag '/servis/alph' do %>
    <%= text_area_tag :txt, @alph %>

    <%= submit_tag "=" %>
<% end %>
<%= text_area_tag :rezz, @rezult %>    

app/views/servis/calc.html.erb
Калькулятор!
<%= form_tag '/servis/calc' do %>
<br />
    <%= text_field_tag :one, @calc %>
    <%= @rez%>

    <%= submit_tag "=" %>
    <%= submit_tag "+" %>
    <%= submit_tag "*" %>
    <%= submit_tag "/" %>
    <%= submit_tag "-" %><br />


    <%= submit_tag "1" %>
    <%= submit_tag "2" %>
    <%= submit_tag "3" %><br />
    <%= submit_tag "4" %>
    <%= submit_tag "5" %>
    <%= submit_tag "6" %><br />
    <%= submit_tag "7" %>
    <%= submit_tag "8" %>
    <%= submit_tag "9" %><br />
    <%= submit_tag "0" %>
    <%= submit_tag "  CE  " %>
<% end %>